/datum/preferences/proc/send_character_ui_resources(mob/user)
	send_grimshart_theme(user)

/datum/preferences/proc/send_grimshart_theme(mob/user)
	// Background
	user << browse_rsc('html/character_ui/grimshart/background&reference/Charsheet_BG.1.png', "Charsheet_BG.1.png")
	// Header
	user << browse_rsc('html/character_ui/grimshart/header/0_header_bg.png', "0_header_bg.png")
	// Character Preview
	user << browse_rsc('html/character_ui/grimshart/character_preview/charpreview_bg.png', "charpreview_bg.png")
	// Body
	user << browse_rsc('html/character_ui/grimshart/body/0_body_bg.png', "0_body_bg.png")
	user << browse_rsc('html/character_ui/grimshart/body/body_age.png', "body_age.png")
	user << browse_rsc('html/character_ui/grimshart/body/body_flaw.png', "body_flaw.png")
	user << browse_rsc('html/character_ui/grimshart/body/body_dominanthand.png', "body_dominanthand.png")
	user << browse_rsc('html/character_ui/grimshart/body/body_ancestry.png', "body_ancestry.png")
	user << browse_rsc('html/character_ui/grimshart/body/body_customize.png', "body_customize.png")
	user << browse_rsc('html/character_ui/grimshart/body/body_bodytype.png', "body_bodytype.png")
	// Voice
	user << browse_rsc('html/character_ui/grimshart/voice/0_voice_bg.png', "0_voice_bg.png")
	user << browse_rsc('html/character_ui/grimshart/voice/voice_type.png', "voice_type.png")
	user << browse_rsc('html/character_ui/grimshart/voice/voice_moans.png', "voice_moans.png")
	user << browse_rsc('html/character_ui/grimshart/voice/voice_colour.png', "voice_colour.png")
	user << browse_rsc('html/character_ui/grimshart/voice/voice_colour_blob.png', "voice_colour_blob.png")
	// Flavour
	user << browse_rsc('html/character_ui/grimshart/flavour/0_flavour_bg.png', "0_flavour_bg.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_culture.png', "flavour_culture.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_descriptors.png', "flavour_descriptors.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_descriptors_hover.png', "flavour_descriptors_hover.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_text.png', "flavour_text.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_text_hover.png', "flavour_text_hover.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_misc.png', "flavour_misc.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_misc_hover.png', "flavour_misc_hover.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_preview.png', "flavour_preview.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_preview_hover.png', "flavour_preview_hover.png")
	// Loadout and stats
	user << browse_rsc('html/character_ui/grimshart/loadout/0_loadout_bg.png', "0_loadout_bg.png")
	user << browse_rsc('html/character_ui/grimshart/loadout/loadout_item1.png', "loadout_item1.png")
	user << browse_rsc('html/character_ui/grimshart/stats/0_stats_bg.png', "0_stats_bg.png")
	// Headshot
	user << browse_rsc('html/character_ui/grimshart/character_headshot/headshot_bg.png', "headshot_bg.png")
	user << browse_rsc('html/character_ui/grimshart/character_headshot/nsfw_headshot_bg.png', "nsfw_headshot_bg.png")
	// OOC
	user << browse_rsc('html/character_ui/grimshart/ooc/0_ooc_bg.png', "0_ooc_bg.png")
	user << browse_rsc('html/character_ui/grimshart/ooc/ooc_notes.png', "ooc_notes.png")
	user << browse_rsc('html/character_ui/grimshart/ooc/ooc_notes_hover.png', "ooc_notes_hover.png")
	user << browse_rsc('html/character_ui/grimshart/ooc/ooc_extra.png', "ooc_extra.png")
	user << browse_rsc('html/character_ui/grimshart/ooc/ooc_extra_hover.png', "ooc_extra_hover.png")
	user << browse_rsc('html/character_ui/grimshart/ooc/ooc_erp.png', "ooc_erp.png")
	user << browse_rsc('html/character_ui/grimshart/ooc/ooc_erp_hover.png', "ooc_erp_hover.png")
	// Features
	user << browse_rsc('html/character_ui/grimshart/features/0_features_bg.png', "0_features_bg.png")
	user << browse_rsc('html/character_ui/grimshart/features/features_bodytype_f.png', "features_bodytype_f.png")
	user << browse_rsc('html/character_ui/grimshart/features/features_bodytype_m.png', "features_bodytype_m.png")
	user << browse_rsc('html/character_ui/grimshart/features/features_button.png', "features_button.png")
	user << browse_rsc('html/character_ui/grimshart/features/features_button_hover.png', "features_button_hover.png")
	user << browse_rsc('html/character_ui/grimshart/features/features_random.png', "features_random.png")
	user << browse_rsc('html/character_ui/grimshart/features/features_random_hover.png', "features_random_hover.png")
	// Misc Buttons
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/ready_order.png', "ready_order.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/ready_order_hover.png', "ready_order_hover.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/change_character.png', "change_character.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/change_character_hover.png', "change_character_hover.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/save.png', "save.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/save_hover.png', "save_hover.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/undo.png', "undo.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/undo_hover.png', "undo_hover.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/done.png', "done.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/done_hover.png', "done_hover.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/keybinds.png', "keybinds.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/keybinds_hover.png', "keybinds_hover.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/toggles.png', "toggles.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/toggles_hover.png', "toggles_hover.png")
